services:
  clangd:
    image: lspcontainers/clangd-language-server
    container_name: atcoder-clangd
    volumes:
      - ./:${PWD}
    working_dir: ${PWD}
    tty: true
  gcc:
    image: gcc:12.2
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
    command: bash -c "g++ -std=c++23 -Wall -o main main.cc && ./main"
