services:
  clangd:
    extends:
      file: ${HOME}/compose.yaml
      service: clangd
  gcc:
    image: gcc:12.2
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
    command: bash -c "g++ -std=c++23 -Wall -o main main.cc && ./main"
