services:
  gcc:
    image: genjiohara/gcc
    container_name: AtCoder
    volumes:
      - ./:/root/workspace
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=$DISPLAY
    working_dir: /root/workspace
    tty: true
